spring.application.name=finance

# Docker Compose
spring.docker.compose.enabled=false

# MongoDB
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.mongodb.database=${SPRING_DATA_MONGODB_DATABASE}
spring.data.mongodb.uuid-representation=standard
