spring.application.name=finance

# Docker Compose
spring.docker.compose.enabled=false

# MongoDB
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.mongodb.database=${SPRING_DATA_MONGODB_DATABASE}
spring.data.mongodb.uuid-representation=standard

# Auth JWT
auth.jwt.secret=${AUTH_JWT_SECRET}
auth.jwt.access-expiration-ms=900000
auth.jwt.refresh-expiration-ms=604800000
